name = "LindCraft"
author = "SugoiDogo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "257274b0c6176efbdfcfd9252c3bed74ea142cb73cb676e1e1af7920596ded34"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
